### ISSUE TITLE
Postar as mensagens do grupo no telegram em uma thread no fórum

### ISSUE THREAD

**Issue by augustogoulart** [henriquebastos/autonobot#2]
As mensagens do grupo do Telegram em geral estão sendo perdidos por quem não está participando da conversa no momento, e como a interação lá está frenética, muito conteúdo bom está sendo perdido. A proposta pra resolver isso é:

1. O bot deve criar uma thread no fórum por dia.
2. O bot deve postar nessa thread todas as mensagens enviadas ao grupo do telegram no dia.

Como o fórum já possui API, isso não deve ser um problema.

**Comment by diegosorrilha** [comment]
A ideia é realmente muito interessante. Porém não sei se vale a pena jogar TUDO o que rola no dia em uma thread. Pode ficar muita informação na thread e não ser lida.

Mas aí entramos em outro problema: Como decidir o que vai para a thread e o que não vai?

**Comment by adrianomargarin** [comment]
Podemos separar na thread de 12 em 12 horas. Assim pega as mensagens das 00:00 as 12:00 e 12:01 até 23:59.

**Comment by augustogoulart** [comment]
@diegosorrilha de início a idéia é pegar tudo mesmo. Não vejo uma forma de filtarmos o que é relevante ou não. Até porque a pegada do Telegram é ser uma mesa de bar, então tudo no fim das contas é relevante.

**Comment by augustogoulart** [comment]
@adrianomargarin Mas isso pode picar a conversa que estiver rolando 12:00. Acho que o primeiro passo é pegar tudo do Telegram e mandar pro fórum. Depois vamos testando como organizar isso.

**Comment by diegosorrilha** [comment]
@augustogoulart Sakei.

Também penso assim.. a única forma de filtrar o que é relevante, seria alguém marcar as msgs, tipo como rola com o /newsletter. 

Mas se o propósito é somente logar o dia numa thread pra quem quiser ler depois, tranquilo. ;)

Acho importante logar os áudios também, tem vários muito bons que rolam lá no grupo :D

Sobre picar de 12 em 12h, acho que pode rolar de quebrar uma conversa tb. De repente se fizermos essa raspagem no meio da madrugada (onde a chance de quebrar uma conversa no meio é bem menor). 
Não sei, mas concordo que o primeiro passo é pegar tudo e jogar no forum ;)

**Comment by henriquebastos** [comment]
Achei interessante a ideia.

Isso precisa ser quebrado em 2 etapas:

### 1) O Bot

O bot recebe as mensagens em tempo real por pooling. Precisaremos adicionar um controle de estado nele para armazenar as mensagens em algum lugar e uma vez ao dia fazer o post no fórum.

Acho que isso vai exigir que tenhamos um canal de teste para validar as coisas. Ao menos para mockarmos o bot com as variações de mensagens que desejamos suportar: texto, audio, imagem, gif, stickers, reply, imagem com descrição, mention

### 2) O fórum

Uma vez que tenhamos os conteúdos para fazer o mock do telegram, temos que definir como cada mensagem será exibida:

1. Como o fórum trabalha com áudios?
2. Como faz upload de imagens, gifs e audios?
3. Formatação de mensagem e resposta.
4. Faremos tipo irc com data e hora?
5. Users do telegram são diferentes dos users do fórum. E se criássemos uma forma de linkar esses 2? Seria útil no fórum mencionar o user em questão? (tá com cheirinho de firula).
