### ISSUE TITLE
Manter o bot ligado. :-P

### ISSUE THREAD

**Issue by henriquebastos** [henriquebastos/autonobot#4]
Hoje o Autonobot só funciona na minha máquina... quando eu lembro de ligar ele... o que acontece mais algumas vezes por semana 🤣 

Com as issues #1 e #2 tá na hora de botar ele num servidorzinho.

O que vocês recomendam?

**Comment by henriquebastos** [comment]
@cuducos @augustogoulart

**Comment by cuducos** [comment]
Freetier do Heroku?

**Comment by cuducos** [comment]
Opa, mandei sem querer antes de terminar… se for fazer deploy numa VM qualquer (Digital Ocean da vida) posso fazer um Dockerfile pra isso : )

**Comment by henriquebastos** [comment]
O problema do Heroku é que ele bota a o dyno pra dormir de tempos em
tempos. Será que isso é irrelevante pro nosso problema?

O que vc acha?

**Comment by cuducos** [comment]
> O problema do Heroku é que ele bota a o dyno pra dormir de tempos em
tempos. Será que isso é irrelevante pro nosso problema?

Acho que só fique mais lento, mas não sei se seria problema mesmo (tipo, de quebrar o bot)… o lance é ver se a requisição vindo do Telegram é entendida pelo Heroku para acordar.

Digital Ocean ou similares eu sei que funcionaria, mas 5 dólares/mês só pra isso não sei se é o ideal…

**Comment by augustogoulart** [comment]
O Heroku bota o dyno pra dormir depois de 30 min de inatividade, mas como o bot fica em long pooling, não teremos tempo de inatividade, certo?

**Comment by dubirajara** [comment]
@henriquebastos @cuducos eu tenho um bot do slack rodando numa dyno gratis no heroku, é verdad que o dyno dorme por inatividade, mais cuando chama ele, ele acorda e funciona, demora algum segundo mais, mas vale a pena por ser gratis, isso no Slack, no telegram nao provei, mais deve ser a mesma coisa.

**Comment by henriquebastos** [comment]
Boa! Então o slack chama o bot por webhook em vez de pooling?

Em 19 de out de 2017 15:08, "Diego Ubirajara" <notifications@github.com>
escreveu:

**Comment by dubirajara** [comment]
sim @henriquebastos  eu acho melhor por webhook, nao sei como seria o funcionamento no telegram, se podia provar pra ver como funcionaria!

**Comment by henriquebastos** [comment]
Done! Botei no Heroku! Tá redondo!
